### ISSUE TITLE
Failed to play songs on Spotify

### ISSUE THREAD

**Issue by gcampax** [stanford-oval/thingpedia-common-devices#180]
It seems the API call failed with "Player command failed: Restriction violated" (HTTP 403).
Is it possible the problem is setting shuffle to false when it was already false?

Full log:

```
Sep 10 12:42:53 crowdie thingengine-child-1[11684]: Analyzed message into $dialogue @org.thingpedia.dialogue.transaction.execute ; now => ( @com.spotify.song ) filter param:artists contains " taylor swift " ^^com.spotify:artist => @com.spotify.play_song on param:song = param:id ;
Sep 10 12:42:53 crowdie thingengine-child-1[11684]: searching for  https://api.spotify.com/v1/search?q=artist%3A%22taylor%20swift%22&type=artist&market=from_token&limit=5
Sep 10 12:42:53 crowdie thingengine-child-1[11684]: searching for  https://api.spotify.com/v1/search?q=artist%3A%22taylor%20swift%22&type=track&market=from_token&limit=20
Sep 10 12:42:54 crowdie thingengine-child-1[11684]: false
Sep 10 12:42:54 crowdie thingengine-child-1[11684]: setting active device
Sep 10 12:42:54 crowdie thingengine-child-1[11684]: setting shuffle: false
Sep 10 12:42:54 crowdie thingengine-child-1[11684]: Initializing dialogue policy for devices: com.forismatic.quotes, com.icanhazdadjoke, com.spotify
Sep 10 12:42:54 crowdie thingengine-child-1[11684]: false
Sep 10 12:42:54 crowdie thingengine-child-1[11684]: setting active device
Sep 10 12:42:54 crowdie thingengine-child-1[11684]: https://api.spotify.com/v1/me/player/shuffle?state=false&device_id=b305db3b61d1c95661290444e9ddef901ccfff60
Sep 10 12:42:54 crowdie thingengine-child-1[11684]: Loaded 3 devices
Sep 10 12:42:54 crowdie thingengine-child-1[11684]: Loaded 17 templates
Sep 10 12:42:54 crowdie thingengine-child-1[11684]: --- DEPTH 0
Sep 10 12:42:54 crowdie thingengine-child-1[11684]: depth 0 took 0.01 seconds
Sep 10 12:42:54 crowdie thingengine-child-1[11684]: --- DEPTH 1
Sep 10 12:42:54 crowdie thingengine-child-1[11684]: depth 1 took 0.03 seconds
Sep 10 12:42:54 crowdie thingengine-child-1[11684]: --- DEPTH 2
Sep 10 12:42:54 crowdie thingengine-child-1[11684]: depth 2 took 0.03 seconds
Sep 10 12:42:54 crowdie thingengine-child-1[11684]: --- DEPTH 3
Sep 10 12:42:54 crowdie thingengine-child-1[11684]: depth 3 took 0.17 seconds
Sep 10 12:42:54 crowdie thingengine-child-1[11684]: --- DEPTH 4
Sep 10 12:42:55 crowdie thingengine-child-1[11684]: depth 4 took 0.39 seconds
Sep 10 12:42:55 crowdie thingengine-child-1[11684]: --- DEPTH 5
Sep 10 12:42:55 crowdie thingengine-child-1[11684]: depth 5 took 0.00 seconds
Sep 10 12:42:55 crowdie thingengine-child-1[11684]: --- DEPTH 6
Sep 10 12:42:55 crowdie thingengine-child-1[11684]: depth 6 took 0.00 seconds
Sep 10 12:42:55 crowdie thingengine-child-1[11684]: --- DEPTH 7
Sep 10 12:42:55 crowdie thingengine-child-1[11684]: depth 7 took 0.00 seconds
Sep 10 12:42:55 crowdie thingengine-child-1[11684]: HTTP request failed: {
Sep 10 12:42:55 crowdie thingengine-child-1[11684]:   "error" : {
Sep 10 12:42:55 crowdie thingengine-child-1[11684]:     "status" : 403,
Sep 10 12:42:55 crowdie thingengine-child-1[11684]:     "message" : "Player command failed: Restriction violated",
Sep 10 12:42:55 crowdie thingengine-child-1[11684]:     "reason" : "UNKNOWN"
Sep 10 12:42:55 crowdie thingengine-child-1[11684]:   }
Sep 10 12:42:55 crowdie thingengine-child-1[11684]: }
Sep 10 12:42:55 crowdie thingengine-child-1[11684]: (node:2) UnhandledPromiseRejectionWarning: Error: Player command failed: Restriction violated
Sep 10 12:42:55 crowdie thingengine-child-1[11684]:     at Tp.Helpers.Http.request.catch (/app/cache/device-classes/com.spotify/index.js:76:23)
Sep 10 12:42:55 crowdie thingengine-child-1[11684]:     at process._tickCallback (internal/process/next_tick.js:68:7)
Sep 10 12:42:55 crowdie thingengine-child-1[11684]: (node:2) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
Sep 10 12:42:55 crowdie thingengine-child-1[11684]: (node:2) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by gcampax** [comment]
As a further point of debugging: when I tried this command, my Spotify was paused on a podcast track, and the UI was not showing the shuffle button at all. The command worked when I switched to playing a regular song.

**Comment by gcampax** [comment]
I believe we fixed this, by showing a friendly error in the Firefox web player.
