### ISSUE TITLE
Error in Home Assistant on upgrades

### ISSUE THREAD

**Issue by gcampax** [stanford-oval/thingpedia-common-devices#276]
```
Device failed to stop: this._unsubscribe is not a function
TypeError: this._unsubscribe is not a function
    at HomeAssistantDeviceSet.stop (/data/almond-server/cache/device-classes/io.home-assistant/index.js:178:18)
    at HomeAssistantGateway.stop (/data/almond-server/cache/device-classes/io.home-assistant/index.js:293:32)
    at DeviceDatabase._notifyDeviceRemoved (/opt/almond/node_modules/genie-toolkit/dist/lib/engine/devices/database.js:242:30)
    at DeviceDatabase.reloadDevice (/opt/almond/node_modules/genie-toolkit/dist/lib/engine/devices/database.js:347:20)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Promise.all (index 0)
```

**Comment by gcampax** [comment]
I think this error occurs when the skill itself upgrades while Almond is running. I think it's just a missing/misnamed method somewhere when the stop() method is called on the skill.

**Comment by gcampax** [comment]
I think this was fixed eventually (it was a missing await)
