### ISSUE TITLE
(Staging) "play podcast" returns unexpected error

### ISSUE THREAD

**Issue by tonyespinoza1** [stanford-oval/thingpedia-common-devices#415]
![image](https://user-images.githubusercontent.com/86493411/128796620-18ccb7a9-6246-4e98-a591-a1b4af53778b.png)

![image](https://user-images.githubusercontent.com/86493411/128796853-4077a57a-d90b-4d4c-9397-95cfed29bfd1.png)

```
====
# main/176f1e1d-0ba9-444c-ab05-9071a9734340
#! timestamp: 2021-08-10T02:18:05.933Z
U: play podcast
UT: $dialogue @org.thingpedia.dialogue.transaction.execute;
UT: @org.thingpedia.media-source.show() => @org.thingpedia.media-player.play(playable=id);
C: $dialogue @org.thingpedia.dialogue.transaction.execute;
C: @org.thingpedia.media-source(id="com.spotify-126743886"^^tt:device_id("Spotify Account of Tony Espinoza")).show() => @org.thingpedia.media-player(id="com.spotify-126743886"^^tt:device_id("Spotify Account of Tony Espinoza")).play(playable=id)
C: #[results=[
C:   { device="93f56161fd84ab2dffb3387154e75d2199d1de46"^^org.thingpedia.media-player:device("Tony's Mac Pro"), playable="spotify:show:5ZKHbyeo97VivPN05bXt8r"^^org.thingpedia.media-source:playable("Good Times with Mo: The Podcast Year 10"), __device="com.spotify-126743886"^^tt:device_id("Spotify Account of Tony Espinoza") },
C:   { device="93f56161fd84ab2dffb3387154e75d2199d1de46"^^org.thingpedia.media-player:device("Tony's Mac Pro"), playable="spotify:show:1TZWDLIrcaPgq7kQAyOqfQ"^^org.thingpedia.media-source:playable("Year End Reflection"), __device="com.spotify-126743886"^^tt:device_id("Spotify Account of Tony Espinoza") },
C:   { device="93f56161fd84ab2dffb3387154e75d2199d1de46"^^org.thingpedia.media-player:device("Tony's Mac Pro"), playable="spotify:show:0F0bomQrdLbPjz4nxRVjiI"^^org.thingpedia.media-source:playable("Ultimate Mock Draft 2021 - Pro Basketball Draft Simulation"), __device="com.spotify-126743886"^^tt:device_id("Spotify Account of Tony Espinoza") },
C:   { device="93f56161fd84ab2dffb3387154e75d2199d1de46"^^org.thingpedia.media-player:device("Tony's Mac Pro"), playable="spotify:show:3CpR3dGT55X7ZxUfJ0mS7S"^^org.thingpedia.media-source:playable("Come Follow Me 2021 - Doctrine and Covenants"), __device="com.spotify-126743886"^^tt:device_id("Spotify Account of Tony Espinoza") },
C:   { device="93f56161fd84ab2dffb3387154e75d2199d1de46"^^org.thingpedia.media-player:device("Tony's Mac Pro"), playable="spotify:show:21JT1fT5BauYygwzWhXqzm"^^org.thingpedia.media-source:playable("Commencement: Speeches For The Class of 2021"), __device="com.spotify-126743886"^^tt:device_id("Spotify Account of Tony Espinoza") }
C: ]]
C: #[error="invalid id"]
C: #[error_detail="invalid id"]
C: #[error_stack="Error: invalid id\n    at /srv/thingengine/cache/device-classes/com.spotify/index.js:100:23\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)\n    at async SpotifyDevice.shows_get_unplayed_episodes (/srv/thingengine/cache/device-classes/com.spotify/index.js:1079:37)\n    at async SpotifyDevice._flushPlay (/srv/thingengine/cache/device-classes/com.spotify/index.js:1136:44)\n    at async /srv/thingengine/cache/device-classes/com.spotify/index.js:1011:17\n    at async ExecWrapper.exitProcedure (/opt/almond-cloud/node_modules/genie-toolkit/dist/lib/engine/apps/exec_wrapper.js:175:13)\n    at async eval (eval at compile (/opt/almond-cloud/node_modules/thingtalk/dist/compiler/jsir.js:780:46), <anonymous>:67:5)\n    at async RuleExecutor._ruleThread (/opt/almond-cloud/node_modules/genie-toolkit/dist/lib/engine/apps/rule_executor.js:61:13)"];
#! timestamp: 2021-08-10T02:18:07.318Z
A: Sorry, there was an unexpected error with your command. Please try again later or report this issue to my developers.
AT: $dialogue @org.thingpedia.dialogue.transaction.sys_action_error;
#! timestamp: 2021-08-10T02:19:33.297Z
U: cancel
UT: $dialogue @org.thingpedia.dialogue.transaction.cancel;
C: $dialogue @org.thingpedia.dialogue.transaction.cancel;
C: @org.thingpedia.media-source(id="com.spotify-126743886"^^tt:device_id("Spotify Account of Tony Espinoza")).show() => @org.thingpedia.media-player(id="com.spotify-126743886"^^tt:device_id("Spotify Account of Tony Espinoza")).play(playable=id)
C: #[results=[
C:   { device="93f56161fd84ab2dffb3387154e75d2199d1de46"^^org.thingpedia.media-player:device("Tony's Mac Pro"), playable="spotify:show:5ZKHbyeo97VivPN05bXt8r"^^org.thingpedia.media-source:playable("Good Times with Mo: The Podcast Year 10"), __device="com.spotify-126743886"^^tt:device_id("Spotify Account of Tony Espinoza") },
C:   { device="93f56161fd84ab2dffb3387154e75d2199d1de46"^^org.thingpedia.media-player:device("Tony's Mac Pro"), playable="spotify:show:1TZWDLIrcaPgq7kQAyOqfQ"^^org.thingpedia.media-source:playable("Year End Reflection"), __device="com.spotify-126743886"^^tt:device_id("Spotify Account of Tony Espinoza") },
C:   { device="93f56161fd84ab2dffb3387154e75d2199d1de46"^^org.thingpedia.media-player:device("Tony's Mac Pro"), playable="spotify:show:0F0bomQrdLbPjz4nxRVjiI"^^org.thingpedia.media-source:playable("Ultimate Mock Draft 2021 - Pro Basketball Draft Simulation"), __device="com.spotify-126743886"^^tt:device_id("Spotify Account of Tony Espinoza") },
C:   { device="93f56161fd84ab2dffb3387154e75d2199d1de46"^^org.thingpedia.media-player:device("Tony's Mac Pro"), playable="spotify:show:3CpR3dGT55X7ZxUfJ0mS7S"^^org.thingpedia.media-source:playable("Come Follow Me 2021 - Doctrine and Covenants"), __device="com.spotify-126743886"^^tt:device_id("Spotify Account of Tony Espinoza") },
C:   { device="93f56161fd84ab2dffb3387154e75d2199d1de46"^^org.thingpedia.media-player:device("Tony's Mac Pro"), playable="spotify:show:21JT1fT5BauYygwzWhXqzm"^^org.thingpedia.media-source:playable("Commencement: Speeches For The Class of 2021"), __device="com.spotify-126743886"^^tt:device_id("Spotify Account of Tony Espinoza") }
C: ]]
C: #[error="invalid id"]
C: #[error_detail="invalid id"]
C: #[error_stack="Error: invalid id\n    at /srv/thingengine/cache/device-classes/com.spotify/index.js:100:23\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)\n    at async SpotifyDevice.shows_get_unplayed_episodes (/srv/thingengine/cache/device-classes/com.spotify/index.js:1079:37)\n    at async SpotifyDevice._flushPlay (/srv/thingengine/cache/device-classes/com.spotify/index.js:1136:44)\n    at async /srv/thingengine/cache/device-classes/com.spotify/index.js:1011:17\n    at async ExecWrapper.exitProcedure (/opt/almond-cloud/node_modules/genie-toolkit/dist/lib/engine/apps/exec_wrapper.js:175:13)\n    at async eval (eval at compile (/opt/almond-cloud/node_modules/thingtalk/dist/compiler/jsir.js:780:46), <anonymous>:67:5)\n    at async RuleExecutor._ruleThread (/opt/almond-cloud/node_modules/genie-toolkit/dist/lib/engine/apps/rule_executor.js:61:13)"];
#! timestamp: 2021-08-10T02:19:33.325Z
A: Alright, let me know if I can help you with anything else!
AT: $dialogue @org.thingpedia.dialogue.transaction.sys_end;
====
# main/47f0642d-f708-4605-8b5c-2f4c340480c1
#! timestamp: 2021-08-10T02:19:36.347Z
U: play podcast
UT: $dialogue @org.thingpedia.dialogue.transaction.execute;
UT: @org.thingpedia.media-source.show() => @org.thingpedia.media-player.play(playable=id);
cancel
```

**Comment by nrser** [comment]
@jmhw0123 Spotify skill issue @tonyespinoza1 and I just ran into, what do you think?

**Comment by tonyespinoza1** [comment]
@jmhw0123 just wanted to check and see if this can be fixed quickly.  i would like to demo it to monica on Friday.
