### ISSUE TITLE
Error in Bing skill with unrelated command

### ISSUE THREAD

**Issue by gcampax** [stanford-oval/thingpedia-common-devices#423]
From the scenario tests:

```
Genie says: Sorry, I had an error processing your command: Cannot read property'0' of undefined.
TypeError: Cannot read property '0' of undefined
    at BingDialogueHandler.analyzeCommand (/home/travis/build/stanford-oval/thingpedia-common-devices/main/com.bing/index.js:48:558)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async ThingpediaDialogueHandler.analyzeCommand (/home/travis/build/stanford-oval/thingpedia-common-devices/node_modules/genie-toolkit/dist/lib/dialogue-agent/handlers/3rdparty.js:109:23)
    at async DialogueLoop._analyzeCommand (/home/travis/build/stanford-oval/thingpedia-common-devices/node_modules/genie-toolkit/dist/lib/dialogue-agent/dialogue-loop.js:173:34)
    at async DialogueLoop._handleUserInput (/home/travis/build/stanford-oval/thingpedia-common-devices/node_modules/genie-toolkit/dist/lib/dialogue-agent/dialogue-loop.js:291:41)
    at async DialogueLoop._loop (/home/travis/build/stanford-oval/thingpedia-common-devices/node_modules/genie-toolkit/dist/lib/dialogue-agent/dialogue-loop.js:354:21)
Invalid reply: Sorry, I had an error processing your command: Cannot read property'0' of undefined.
>> expecting = null
```

(full log: https://api.travis-ci.com/v3/job/532062796/log.txt )

**Comment by gcampax** [comment]
Cannot reproduce, likely fixed by other changes in Bing.
