### ISSUE TITLE
Error in bing skill

### ISSUE THREAD

**Issue by gcampax** [stanford-oval/thingpedia-common-devices#430]
From the scenario tests:
```
TypeError: bestRankingItems.push is not iterable (cannot read property Symbol(Symbol.iterator))
    at BingDialogueHandler.analyzeCommand (/home/travis/build/stanford-oval/thingpedia-common-devices/main/com.bing/index.js:48:676)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async ThingpediaDialogueHandler.analyzeCommand (/home/travis/build/stanford-oval/thingpedia-common-devices/node_modules/genie-toolkit/dist/lib/dialogue-agent/handlers/3rdparty.js:109:23)
    at async DialogueLoop._analyzeCommand (/home/travis/build/stanford-oval/thingpedia-common-devices/node_modules/genie-toolkit/dist/lib/dialogue-agent/dialogue-loop.js:173:34)
    at async DialogueLoop._handleUserInput (/home/travis/build/stanford-oval/thingpedia-common-devices/node_modules/genie-toolkit/dist/lib/dialogue-agent/dialogue-loop.js:291:41)
    at async DialogueLoop._loop (/home/travis/build/stanford-oval/thingpedia-common-devices/node_modules/genie-toolkit/dist/lib/dialogue-agent/dialogue-loop.js:354:21)
Invalid reply: Sorry, I had an error processing your command: bestRankingItems.push is not iterable (cannot read property Symbol(Symbol.iterator)).
>> expecting = null
```

**Comment by gcampax** [comment]
Scenario tests have been happy for a while, I think this was fixed.
