### ISSUE TITLE
"Resume music" crashes server if no Spotify player available

### ISSUE THREAD

**Issue by gcampax** [stanford-oval/thingpedia-common-devices#460]
```
CustomError: No player is available to complete this request
    at AudioController.requestAudio (/opt/almond-cloud/node_modules/genie-toolkit/dist/lib/dialogue-agent/audio/controller.js:197:19)
    at Proxy._negotiatePlay (/srv/thingengine/cache/device-classes/com.spotify/dist/spotify_device/spotify_device.js:193:37)
    at Proxy.do_player_play (/srv/thingengine/cache/device-classes/com.spotify/dist/spotify_device/spotify_device.js:409:14)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async SpotifyDevice.descriptor.value (/srv/thingengine/cache/device-classes/com.spotify/dist/spotify_device/spotify_device_helpers.js:133:24)
    at async ExecWrapper.invokeAction (/opt/almond-cloud/node_modules/genie-toolkit/dist/lib/engine/apps/exec_wrapper.js:243:26)
    at async eval (eval at compile (/opt/almond-cloud/node_modules/thingtalk/dist/compiler/jsir.js:774:46), <anonymous>:16:25)
    at async RuleExecutor._ruleThread (/opt/almond-cloud/node_modules/genie-toolkit/dist/lib/engine/apps/rule_executor.js:61:13) {
  code: 'unsupported'
}
```

**Comment by gcampax** [comment]
In fact, it's not related to Spotify players, but to AudioController players. Any web use of Spotify will trigger this bug.
